// SPDX-License-Identifier: Apache-2.0
// Two renderings of one run: JSON for the gate and for a later diff, Markdown for a reader.
//
// Every figure carries the machine, the corpus size, the sample count and the date, because
// a millisecond without those four is not a measurement. Where a value could not be taken it
// is the string `NOT MEASURED: <reason>` in both renderings, so it survives serialisation as
// a stated absence rather than degrading to a zero.

import type { AxisResult } from './axes/axis.ts'
import type { ScaleRow } from './axes/a4-latency.ts'
import type { BenchConfig } from './config.ts'
import type { Corpus } from './corpus.ts'
import type { Floors } from './floors.ts'
import type { GateReport } from './gate.ts'
import type { Machine } from './machine.ts'
import type { PackageFacts } from './package-facts.ts'
import type { Accounting, TokenizerLoad } from './tokens.ts'
import type { Measurement, Stats } from './timing.ts'

export type RunReport = {
  readonly runId: string
  readonly startedAt: string
  readonly finishedAt: string
  readonly durationMs: number
  readonly machine: Machine
  readonly config: BenchConfig
  readonly floors: Floors
  readonly corpora: readonly Corpus[]
  readonly latency: readonly ScaleRow[]
  readonly packageFacts: PackageFacts
  readonly tokenizers: readonly { readonly name: string; readonly package: string; readonly version: string | null; readonly loaded: boolean; readonly reason?: string }[]
  readonly accounting: readonly Accounting[]
  readonly axes: readonly AxisResult[]
  readonly gate: GateReport
}

export function tokenizerFacts(loaded: readonly TokenizerLoad[]): RunReport['tokenizers'] {
  return loaded.map((t) => (t.ok
    ? { name: t.name, package: t.package, version: t.version, loaded: true }
    : { name: t.name, package: t.package, version: null, loaded: false, reason: t.reason }))
}

const ms = (n: number): string => n.toFixed(1)

function statsCells(s: Stats): string {
  return `${ms(s.firstRunMs)} | ${ms(s.minMs)} | ${ms(s.p50.ms)} | ${ms(s.p95.ms)} | ${ms(s.p99.ms)} | ${s.p99.rank}/${s.p99.of}`
}

function measurementRow(name: string, m: Measurement): string {
  const net = m.net === undefined ? 'n/a' : ms(m.net.p95.ms)
  const inp = m.inProcess === undefined ? 'NOT MEASURED' : ms(m.inProcess.p95.ms)
  const rss = m.peakRssKb === undefined ? 'NOT MEASURED' : `${(m.peakRssKb / 1024).toFixed(1)}`
  const failed = m.failures.length === 0 ? '' : ` **${m.failures.length} failed: ${m.failures[0]}**`
  return `| ${name} | ${m.wall.n} | ${m.opsTotal} | ${statsCells(m.wall)} | ${net} | ${inp} | ${rss} |${failed}`
}

function bytes(n: number | string): string {
  return typeof n === 'string' ? n : n >= 1024 * 1024 ? `${(n / (1024 * 1024)).toFixed(1)} MiB` : `${(n / 1024).toFixed(1)} KiB`
}

export function toMarkdown(report: RunReport): string {
  const out: string[] = []
  const push = (...lines: string[]): void => { out.push(...lines) }

  push(`# treadle benchmark run ${report.runId}`, '')
  push(`Started ${report.startedAt}, finished ${report.finishedAt}, ${(report.durationMs / 1000).toFixed(1)} s of wall time.`)
  push('Generated by `npm run bench`. Every figure below was measured in that run; nothing is carried over, interpolated or estimated.')
  push('')

  push('## Machine and runtime', '')
  push('| Fact | Value |', '|---|---|')
  push(`| Machine | ${report.machine.cpuModel}, ${report.machine.cores} cores, ${(report.machine.memoryBytes / 1024 ** 3).toFixed(0)} GB, ${report.machine.platform} ${report.machine.release} (${report.machine.arch}) |`)
  push(`| Node | ${report.machine.node} (V8 ${report.machine.v8}) |`)
  push(`| SQLite in Node | ${report.machine.sqlite} |`)
  push(`| Declared floor | ${report.machine.declaredNodeFloor}; this runtime ${report.machine.nodeMeetsFloor ? 'meets it' : '**is below it**, so every figure here was taken under a runtime the package refuses'} |`)
  push(`| Seed | ${report.config.seed} |`)
  push('')

  push('## What the harness itself costs', '')
  push('Each row is a strict superset of the one above it, so a difference prices exactly one thing.')
  push('The spawn floor is subtracted from every net column below; the node floor is what the CI gate compares against.')
  push('')
  push('| Floor | n | ops | first | best | p50 | p95 | p99 | p99 rank | net p95 | in-process p95 | peak MiB |', '|---|---|---|---|---|---|---|---|---|---|---|---|')
  for (const row of report.floors.rows) push(measurementRow(row.label, row))
  push('')
  push(`Type stripping costs ${typeof report.floors.typeStrippingMs === 'number' ? `${ms(report.floors.typeStrippingMs)} ms` : report.floors.typeStrippingMs} at the median, and loading the store adapter costs ${typeof report.floors.storeLoadMs === 'number' ? `${ms(report.floors.storeLoadMs)} ms` : report.floors.storeLoadMs} on top of that.`)
  push('DR1 measured its budget on a 406 KB bundle. This tree has no build step, so every figure below runs from TypeScript source and carries both of those costs.')
  push('')

  push('## Corpora', '')
  push('Written through the landed store, not synthesised as files. Item counts are read back from the store after generation.')
  push('')
  push('| Items in store | Shards | Largest shard | ready matches | Records bytes | Events bytes | Index bytes | Generated |', '|---|---|---|---|---|---|---|---|')
  for (const c of report.corpora) {
    push(`| ${c.itemsInStore} | ${c.months.length} | ${c.largestMonth}: ${c.largestMonthItems} records, ${bytes(c.largestMonthBytes)} | ${c.readyMatches} | ${bytes(c.bytes.items)} | ${bytes(c.bytes.events)} | ${bytes(c.bytes.index)} | ${c.reused ? 'reused from cache' : `${((c.generatedMs ?? 0) / 1000).toFixed(1)} s`} |`)
  }
  push('')

  push('## Latency, one cold process per sample', '')
  push('`net p95` is the wall p95 with the spawn floor removed. `in-process p95` excludes Node startup and module loading entirely, which is the form axis A4 targets.')
  push('These are store operations, not commands. The command layer does not exist in this tree.')
  push('')
  for (const scale of report.latency) {
    push(`### ${scale.items} items, ${scale.shards} shards, largest shard ${scale.largestShardRecords} records`, '')
    push('| Operation | n | ops | first | best | p50 | p95 | p99 | p99 rank | net p95 | in-process p95 | peak MiB |', '|---|---|---|---|---|---|---|---|---|---|---|---|')
    for (const [op, m] of Object.entries(scale.operations)) push(measurementRow(op, m))
    push('')
    push(`First index build with the index deleted: ${typeof scale.firstIndexBuildMs === 'number' ? `${scale.firstIndexBuildMs} ms` : scale.firstIndexBuildMs}. Re-index after a hand edit of the largest shard: ${typeof scale.reindexAfterHandEditMs === 'number' ? `${scale.reindexAfterHandEditMs} ms` : scale.reindexAfterHandEditMs}. Both in-process, one sample each.`)
    push('')
  }

  push('## Byte and token accounting', '')
  push('| Tokenizer | Package | Version | Loaded |', '|---|---|---|---|')
  for (const t of report.tokenizers) push(`| ${t.name} | \`${t.package}\` | ${t.version ?? 'NOT MEASURED'} | ${t.loaded ? 'yes' : `no: ${t.reason}`} |`)
  push('')
  push('| Artefact | Bytes | Lines | claude | o200k | cl100k | B/token claude | B/token o200k | B/token cl100k |', '|---|---|---|---|---|---|---|---|---|')
  for (const a of report.accounting) {
    push(`| ${a.label} | ${a.bytes} | ${a.lines} | ${a.tokens.claude} | ${a.tokens.o200k} | ${a.tokens.cl100k} | ${a.bytesPerToken.claude} | ${a.bytesPerToken.o200k} | ${a.bytesPerToken.cl100k} |`)
  }
  push('')

  push('## Package', '')
  push('| Fact | Value |', '|---|---|')
  push(`| Runtime dependencies | ${report.packageFacts.runtimeDependencies} |`)
  push(`| Development dependencies | ${report.packageFacts.devDependencies} |`)
  push(`| Packed | ${bytes(report.packageFacts.packedBytes)} |`)
  push(`| Unpacked | ${bytes(report.packageFacts.unpackedBytes)} |`)
  push(`| Files in the package | ${report.packageFacts.fileCount} |`)
  push(`| Bundle | ${bytes(report.packageFacts.bundleBytes)} |`)
  push('')

  push('## The twelve comparison axes', '')
  push('| Axis | Verdict | Observed | Reference | Target | ops | samples |', '|---|---|---|---|---|---|---|')
  for (const a of report.axes) {
    push(`| ${a.axis} ${a.name} | ${a.verdict} | ${a.observed} | ${a.reference} | ${a.target} | ${a.operations} | ${a.samples} |`)
  }
  push('')
  const blocked = report.axes.filter((a) => a.blockedOn !== undefined)
  if (blocked.length > 0) {
    push('### What each unfilled axis is waiting for', '')
    for (const a of blocked) push(`- **${a.axis}**: ${a.blockedOn}`)
    push('')
  }

  push('## DR8 budget gate', '')
  push(`Tolerance ${report.gate.tolerancePercent}% over the committed limit. Limits derived from run ${report.gate.derivedFrom.runId} on ${report.gate.derivedFrom.date} (${report.gate.derivedFrom.machine}, Node ${report.gate.derivedFrom.node}).`)
  push(`${report.gate.rows.length} budgets: ${report.gate.passed} pass, ${report.gate.failed} fail, ${report.gate.openMisses} open miss, ${report.gate.pending} pending.`)
  push('An open miss is a budget the product has never met. It is reported with its number and does not fail a build for standing still; a regression against a budget that was met does.')
  push('')
  push('| Budget | Observed | Limit | Unit | Status | Note |', '|---|---|---|---|---|---|')
  for (const r of report.gate.rows) {
    push(`| ${r.budget} | ${r.observed} | ${r.limit} | ${r.unit} | ${r.status.toUpperCase()} | ${r.note ?? ''} |`)
  }
  push('')

  return out.join('\n')
}
