// SPDX-License-Identifier: Apache-2.0
// Two renderings of one run: JSON for the gate and for a later diff, Markdown for a reader.
//
// Every figure carries the machine, the corpus size, the sample count and the date, because
// a millisecond without those four is not a measurement. Where a value could not be taken it
// is the string `NOT MEASURED: <reason>` in both renderings, so it survives serialisation as
// a stated absence rather than degrading to a zero.

import type { AxisResult } from './axes/axis.ts'
import type { QuestionRow } from './axes/a2-questions.ts'
import type { OutputRow } from './axes/a3-output.ts'
import type { ScenarioRow, SeamRow } from './axes/a6-mis-target.ts'
import type { ValidationRow } from './axes/a10-validation.ts'
import type { ContractRow } from './axes/a12-contract.ts'
import type { ScaleRow } from './axes/a4-latency.ts'
import type { BenchConfig } from './config.ts'
import type { Corpus } from './corpus.ts'
import type { Floors } from './floors.ts'
import type { GateReport } from './gate.ts'
import type { LoadSample } from './load.ts'
import type { Machine } from './machine.ts'
import type { PackageFacts } from './package-facts.ts'
import type { Accounting, TokenizerLoad } from './tokens.ts'
import type { Measurement, Stats } from './timing.ts'

export type RunReport = {
  readonly runId: string
  readonly startedAt: string
  readonly finishedAt: string
  readonly durationMs: number
  readonly machine: Machine
  readonly machineState: { readonly atStart: LoadSample; readonly atEnd: LoadSample }
  readonly config: BenchConfig
  readonly floors: Floors
  readonly corpora: readonly Corpus[]
  readonly latency: readonly ScaleRow[]
  readonly packageFacts: PackageFacts
  readonly tokenizers: readonly { readonly name: string; readonly package: string; readonly version: string | null; readonly loaded: boolean; readonly reason?: string }[]
  readonly accounting: readonly Accounting[]
  readonly outputBudgets: readonly OutputRow[]
  readonly axes: readonly AxisResult[]
  readonly gate: GateReport
}

export function tokenizerFacts(loaded: readonly TokenizerLoad[]): RunReport['tokenizers'] {
  return loaded.map((t) => (t.ok
    ? { name: t.name, package: t.package, version: t.version, loaded: true }
    : { name: t.name, package: t.package, version: null, loaded: false, reason: t.reason }))
}

const ms = (n: number): string => n.toFixed(1)

function statsCells(s: Stats): string {
  return `${ms(s.firstRunMs)} | ${ms(s.minMs)} | ${ms(s.p50.ms)} | ${ms(s.p95.ms)} | ${ms(s.p99.ms)} | ${s.p99.rank}/${s.p99.of}`
}

function measurementRow(name: string, m: Measurement): string {
  const net = m.net === undefined ? 'n/a' : ms(m.net.p95.ms)
  const inp = m.inProcess === undefined ? 'NOT MEASURED' : ms(m.inProcess.p95.ms)
  const rss = m.peakRssKb === undefined ? 'NOT MEASURED' : `${(m.peakRssKb / 1024).toFixed(1)}`
  const failed = m.failures.length === 0 ? '' : ` **${m.failures.length} failed: ${m.failures[0]}**`
  const load = `${m.load.before.load1} to ${m.load.after.load1}, ${m.load.before.nodeProcesses} node proc`
  return `| ${name} | ${m.wall.n} | ${m.opsTotal} | ${statsCells(m.wall)} | ${net} | ${inp} | ${rss} | ${load} |${failed}`
}

function bytes(n: number | string): string {
  return typeof n === 'string' ? n : n >= 1024 * 1024 ? `${(n / (1024 * 1024)).toFixed(1)} MiB` : `${(n / 1024).toFixed(1)} KiB`
}

export function toMarkdown(report: RunReport): string {
  const out: string[] = []
  const push = (...lines: string[]): void => { out.push(...lines) }

  push(`# treadle benchmark run ${report.runId}`, '')
  push(`Started ${report.startedAt}, finished ${report.finishedAt}, ${(report.durationMs / 1000).toFixed(1)} s of wall time.`)
  push('Generated by `npm run bench`. Every figure below was measured in that run; nothing is carried over, interpolated or estimated.')
  push('')

  push('## Machine and runtime', '')
  push('| Fact | Value |', '|---|---|')
  push(`| Machine | ${report.machine.cpuModel}, ${report.machine.cores} cores, ${(report.machine.memoryBytes / 1024 ** 3).toFixed(0)} GB, ${report.machine.platform} ${report.machine.release} (${report.machine.arch}) |`)
  push(`| Node | ${report.machine.node} (V8 ${report.machine.v8}) |`)
  push(`| SQLite in Node | ${report.machine.sqlite} |`)
  push(`| Declared floor | ${report.machine.declaredNodeFloor}; this runtime ${report.machine.nodeMeetsFloor ? 'meets it' : '**is below it**, so every figure here was taken under a runtime the package refuses'} |`)
  push(`| Seed | ${report.config.seed} |`)
  push('')
  push('This machine is shared with other work and was not idle for this run.')
  push('Rather than wait for quiet, every row below carries the load either side of it, so a figure above its series can be judged against what the machine was doing.')
  push('')
  push('| Machine state | 1m load | 5m | 15m | free MiB | memory used | node processes |', '|---|---|---|---|---|---|---|')
  for (const [when, sample] of [['at the start', report.machineState.atStart], ['at the end', report.machineState.atEnd]] as const) {
    push(`| ${when} | ${sample.load1} | ${sample.load5} | ${sample.load15} | ${sample.freeMemMiB} | ${sample.usedMemPercent}% | ${sample.nodeProcesses} |`)
  }
  const peaks = report.latency.flatMap((s) => Object.values(s.operations).map((m) => m.load.peak1m))
  if (peaks.length > 0) {
    push('')
    push(`Across the ${peaks.length} timed operations the 1-minute load ranged from ${Math.min(...peaks)} to ${Math.max(...peaks)}.`)
  }
  push('')

  push('## What the harness itself costs', '')
  push('Each row is a strict superset of the one above it, so a difference prices exactly one thing.')
  push('The spawn floor is subtracted from every net column below; the node floor is what the CI gate compares against.')
  push('')
  push('| Floor | n | ops | first | best | p50 | p95 | p99 | p99 rank | net p95 | in-process p95 | peak MiB | load 1m, node procs |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|')
  for (const row of report.floors.rows) push(measurementRow(row.label, row))
  push('')
  push(`Type stripping costs ${typeof report.floors.typeStrippingMs === 'number' ? `${ms(report.floors.typeStrippingMs)} ms` : report.floors.typeStrippingMs} and loading the store adapter costs ${typeof report.floors.storeLoadMs === 'number' ? `${ms(report.floors.storeLoadMs)} ms` : report.floors.storeLoadMs} on top of it, both taken from the ${report.floors.derivedFromStatistic}: they are fixed costs, and the cleanest launch of the fifty is the closest thing to an uncontaminated reading of one.`)
  push(`DR1 measured its budget on a 406 KB bundle. The tree now builds one, weighed in the package table above, but the timed children below still run from TypeScript source and carry both of those costs; bundling them is what would make these figures comparable with DR1's.`)
  push('')

  push('## Corpora', '')
  push('Written through the landed store, not synthesised as files. Item counts are read back from the store after generation.')
  push('')
  push('| Items in store | Shards | Largest shard | ready matches | Records bytes | Events bytes | Index bytes | Generated |', '|---|---|---|---|---|---|---|---|')
  for (const c of report.corpora) {
    push(`| ${c.itemsInStore} | ${c.months.length} | ${c.largestMonth}: ${c.largestMonthItems} records, ${bytes(c.largestMonthBytes)} | ${c.readyMatches} | ${bytes(c.bytes.items)} | ${bytes(c.bytes.events)} | ${bytes(c.bytes.index)} | ${c.reused ? 'reused from cache' : `${((c.generatedMs ?? 0) / 1000).toFixed(1)} s`} |`)
  }
  push('')
  push('Each corpus also carries the shapes the four new capabilities added, because a corpus with none of them priced nothing that reads the relation graph and every command reads it.')
  push('')
  push('| Items in store | Sprints | Open sprint | Impediments | Relations | blocks | duplicates | relates_to |', '|---|---|---|---|---|---|---|---|')
  for (const c of report.corpora) {
    push(`| ${c.itemsInStore} | ${c.sprintsWritten} | ${c.openSprint} | ${c.impediments} | ${c.relations.total} | ${c.relations.blocks} | ${c.relations.duplicates} | ${c.relations.relates_to} |`)
  }
  push('')

  push('## Latency, one cold process per sample', '')
  push('`net p95` is the wall p95 with the spawn floor removed. `in-process p95` excludes Node startup and module loading entirely, which is the form axis A4 targets.')
  push('`identity`, `get`, `list`, `create` and `transition` are store operations: the timed children call the store directly so a millisecond is not mostly argument parsing. `workspace` is the read every command performs, and `board`, `next` and `doctor` are the three commands whose cost is not the store\'s; none of the eight renders. What a caller gets back is scored by axes A2, A6, A7, A8, A10 and A12 below, which weigh behaviour rather than time.')
  push('')
  for (const scale of report.latency) {
    push(`### ${scale.items} items, ${scale.shards} shards, largest shard ${scale.largestShardRecords} records`, '')
    push('| Operation | n | ops | first | best | p50 | p95 | p99 | p99 rank | net p95 | in-process p95 | peak MiB | load 1m, node procs |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|')
    for (const [op, m] of Object.entries(scale.operations)) push(measurementRow(op, m))
    push('')
    push(`First index build with the index deleted: ${typeof scale.firstIndexBuildMs === 'number' ? `${scale.firstIndexBuildMs} ms` : scale.firstIndexBuildMs}. Re-index after a hand edit of the largest shard: ${typeof scale.reindexAfterHandEditMs === 'number' ? `${scale.reindexAfterHandEditMs} ms` : scale.reindexAfterHandEditMs}. Both in-process, one sample each.`)
    push(typeof scale.relationCycle === 'string'
      ? `Load-time relation check: ${scale.relationCycle}.`
      : `Load-time relation check over ${scale.relationCycle.edges} edges, one sample, in-process: ${scale.relationCycle.buildMs} ms to build the graph and ${scale.relationCycle.findMs} ms to walk it for a cycle in \`blocks\`, which found ${scale.relationCycle.cycle}. The build is paid by every command; the walk is paid by \`doctor\`.`)
    push('')
  }

  push('## Byte and token accounting', '')
  push('| Tokenizer | Package | Version | Loaded |', '|---|---|---|---|')
  for (const t of report.tokenizers) push(`| ${t.name} | \`${t.package}\` | ${t.version ?? 'NOT MEASURED'} | ${t.loaded ? 'yes' : `no: ${t.reason}`} |`)
  push('')
  push('| Artefact | Bytes | Lines | claude | o200k | cl100k | B/token claude | B/token o200k | B/token cl100k |', '|---|---|---|---|---|---|---|---|---|')
  for (const a of report.accounting) {
    push(`| ${a.label} | ${a.bytes} | ${a.lines} | ${a.tokens.claude} | ${a.tokens.o200k} | ${a.tokens.cl100k} | ${a.bytesPerToken.claude} | ${a.bytesPerToken.o200k} | ${a.bytesPerToken.cl100k} |`)
  }
  push('')

  push('## Output budgets per command', '')
  push('Bytes are the gate and tokens are advisory, per DR8. The budgets are the interface specification\'s section A.3, adjusted upward by four bytes for every occurrence of the binary name, because A.3 was stated against a three-character name.')
  push('The reference column is quoted from the prior-art axes table and was never re-derived here.')
  push('')
  push('| Artefact | Bytes | Budget | Within | claude | o200k | cl100k | B/token claude | Reference | Against reference |', '|---|---|---|---|---|---|---|---|---|---|')
  for (const r of report.outputBudgets) {
    push(`| ${r.artefact} | ${r.bytes} | ${r.allowedBytes} | ${r.withinBudget ? 'yes' : '**no**'} | ${r.tokens.claude} | ${r.tokens.o200k} | ${r.tokens.cl100k} | ${r.bytesPerToken.claude} | ${r.referenceBytes} | ${r.againstReference} |`)
  }
  push('')

  push('## Package', '')
  push('| Fact | Value |', '|---|---|')
  push(`| Runtime dependencies | ${report.packageFacts.runtimeDependencies} |`)
  push(`| Development dependencies | ${report.packageFacts.devDependencies} |`)
  push(`| Packed | ${bytes(report.packageFacts.packedBytes)} |`)
  push(`| Unpacked | ${bytes(report.packageFacts.unpackedBytes)} |`)
  push(`| Files in the package | ${report.packageFacts.fileCount} |`)
  push(`| Bundle | ${bytes(report.packageFacts.bundleBytes)} |`)
  push('')

  push('## The twelve comparison axes', '')
  push('| Axis | Verdict | Observed | Reference | Target | ops | samples | peak load 1m |', '|---|---|---|---|---|---|---|---|')
  for (const a of report.axes) {
    push(`| ${a.axis} ${a.name} | ${a.verdict} | ${a.observed} | ${a.reference} | ${a.target} | ${a.operations} | ${a.samples} | ${a.load === undefined ? 'not sampled' : a.load.peak1m} |`)
  }
  push('')
  const blocked = report.axes.filter((a) => a.blockedOn !== undefined)
  if (blocked.length > 0) {
    push('### What each unfilled axis is waiting for', '')
    for (const a of blocked) push(`- **${a.axis}**: ${a.blockedOn}`)
    push('')
  }

  push(...axisDetail(report))

  push('## DR8 budget gate', '')
  push(`Timing limits are program cost at the median: the operation's wall median minus the runner's own \`node -e\` median, measured in the same job.`)
  push(`Tolerance ${report.gate.tolerancePercent}% over the committed limit, because ${report.gate.toleranceWhy}`)
  push(`Limits derived from run ${report.gate.derivedFrom.runId} on ${report.gate.derivedFrom.date} (${report.gate.derivedFrom.machine}, Node ${report.gate.derivedFrom.node}).`)
  push(`${report.gate.rows.length} budgets: ${report.gate.passed} pass, ${report.gate.failed} fail, ${report.gate.openMisses} open miss, ${report.gate.pending} pending.`)
  push('An open miss is a budget the product has never met. It is reported with its number and does not fail a build for standing still; a regression against a budget that was met does.')
  push('')
  push('| Budget | Observed | Limit | Unit | Status | Note |', '|---|---|---|---|---|---|')
  for (const r of report.gate.rows) {
    push(`| ${r.budget} | ${r.observed} | ${r.limit} | ${r.unit} | ${r.status.toUpperCase()} | ${r.note ?? ''} |`)
  }
  push('')

  return out.join('\n')
}

/** One row per detail table an axis publishes. The full detail is in the JSON beside this. */
function detailOf<T>(report: RunReport, axis: string, key: string): T | undefined {
  const detail = report.axes.find((entry) => entry.axis === axis)?.detail
  if (typeof detail !== 'object' || detail === null) return undefined
  return (detail as Record<string, unknown>)[key] as T | undefined
}

/**
 * The tables a reader needs to check an axis rather than trust it. A2 is published whole,
 * because 25 questions scored by one worker is exactly the figure that has to be auditable;
 * the rest are published where the table is short enough to read, with every row in the JSON.
 */
function axisDetail(report: RunReport): string[] {
  const out: string[] = []
  const push = (...lines: string[]): void => { out.push(...lines) }

  const questions = detailOf<readonly QuestionRow[]>(report, 'A2', 'rows')
  if (questions !== undefined) {
    push('### A2, the 25 questions and how each was scored', '')
    push('One command per question. `full` means the command answers the question whole, `partial` that it answers part of it, `none` that no command in the inventory can be aimed at it.')
    push('The reference scored 4 full, 6 partial and 15 none on this same list.')
    push('')
    push('| # | Question | Command | Exit | Score | What a full answer needs | Note |', '|---|---|---|---|---|---|---|')
    for (const row of questions) {
      push(`| ${row.n} | ${row.question} | \`${row.command}\` | ${row.exit} | ${row.score} | ${row.fullNeeds} | ${row.note} |`)
    }
    push('')
  }

  const scenarios = detailOf<readonly ScenarioRow[]>(report, 'A6', 'rows')
  const seam = detailOf<readonly SeamRow[]>(report, 'A6', 'seam')
  if (scenarios !== undefined) {
    push('### A6, where each write landed', '')
    push('The landing column is read out of both stores after the write, not out of what the command printed.')
    push('')
    push('| Scenario | Exit | Expected | Landed in | Identity printed | Store path printed |', '|---|---|---|---|---|---|')
    for (const row of scenarios) {
      push(`| ${row.scenario} | ${row.exit} | ${row.expected} | ${row.landedIn} | ${row.printedIdentity === '' ? 'none' : row.printedIdentity} | ${row.printedPath === '' ? 'not on this path' : row.printedPath} |`)
    }
    push('')
    if (seam !== undefined) {
      push(`At the store seam, which is where resolution is decided: ${seam.filter((row) => row.correct).length} of ${seam.length} resolutions correct.`)
      push('')
    }
  }

  const walk = detailOf<readonly string[]>(report, 'A7', 'statesVisited')
  const guardRefusals = detailOf<number>(report, 'A7', 'guardRefusalsDuringTheWalk')
  const applied = detailOf<number>(report, 'A7', 'appliedTransitions')
  if (walk !== undefined) {
    push('### A7 and A8, what the walk and the pair sweep did', '')
    push(`A7's walk applied ${applied} transitions and visited ${walk.join(', ')}; ${guardRefusals} attempts on a legal edge were refused by a guard and are not counted as applied.`)
    const rules = detailOf<readonly string[]>(report, 'A8', 'rulesSeen')
    const guarded = detailOf<readonly string[]>(report, 'A8', 'guardRefusedLegalEdges')
    if (rules !== undefined && guarded !== undefined) {
      push(`A8's refusals on illegal pairs named ${rules.join(' and ')}; the legal edges a guard refused were ${guarded.join(', ')}, which is the rule table working rather than failing.`)
    }
    push('')
  }

  const validation = detailOf<readonly ValidationRow[]>(report, 'A10', 'rows')
  if (validation !== undefined) {
    push('### A10, the eleven creation rules and what each refusal named', '')
    push('The eleven are enumerated from the prior-art model: five from its own invalid-at-creation column, six from the field dictionary that column defers to.')
    push('A twelfth row is this product requiring a field the model gives a default, and is reported beside the eleven rather than counted in them.')
    push('')
    push('| # | Rule | Source | Exit | Code | Rule id | Nothing created | Cause |', '|---|---|---|---|---|---|---|---|')
    for (const row of validation) {
      push(`| ${row.beyond ? `${row.n}, beyond the eleven` : row.n} | ${row.rule} | ${row.source} | ${row.exit} | ${row.code} | ${row.ruleId} | ${row.notCreated ? 'yes' : '**no**'} | ${row.cause} |`)
    }
    push('')
  }

  const contract = detailOf<readonly ContractRow[]>(report, 'A12', 'rows')
  if (contract !== undefined) {
    push('### A12, every verb on both paths', '')
    push('A row holds when the object is on the expected stream, the other stream is empty, the exit status matches the path, and the object validates against the schema this repository ships for it.')
    push('')
    push('| Verb | Success schema, exit | Failure schema, exit, code | Both hold |', '|---|---|---|---|')
    for (const verb of [...new Set(contract.map((row) => row.verb))]) {
      const success = contract.find((row) => row.verb === verb && row.path === 'success')
      const failure = contract.find((row) => row.verb === verb && row.path === 'failure')
      const both = success?.holds === true && failure?.holds === true
      push(`| ${verb} | ${success?.schema === '' ? 'no object' : success?.schema}, exit ${success?.exit} | ${failure?.schema === '' ? 'no object' : failure?.schema}, exit ${failure?.exit}, ${failure?.code === '' ? 'no code' : failure?.code} | ${both ? 'yes' : `**no**: ${[success, failure].filter((row) => row?.holds === false).map((row) => `${row?.path} ${row?.failures.join('; ')}`).join(' / ')}`} |`)
    }
    push('')
  }

  return out
}
