// SPDX-License-Identifier: Apache-2.0
// DR1's build: one bundled entry file, built with esbuild. The size limit is not written here.
// It is read from bench/budgets.json, so the build and `npm run bench:gate` weigh the bundle
// against the same number and cannot drift apart.
//
// It also writes schemas/, the other half of what `files` in package.json ships. Neither half
// is committed, and both are generated by this one command, so a tarball packed after a build
// carries a bundle and a set of schemas from the same source. `prepack` would be the obvious
// home for that and would not run: .npmrc sets ignore-scripts=true (threat-model finding F13)
// and test/architecture/supply-chain.test.ts refuses the manifest that declares one.

import { build } from 'esbuild'
import { chmodSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

import { generated } from './generate-schemas.ts'
import { shebangOf } from './shebang.ts'

const root = fileURLToPath(new URL('..', import.meta.url))
const outfile = path.join(root, 'dist', 'treadle.js')
// One source for how the runtime is started. The development entry point already carries the
// line, and a second copy here is a line that can drift while both files still look right.
const shebang = shebangOf(root)

const budgets = JSON.parse(readFileSync(path.join(root, 'bench', 'budgets.json'), 'utf8')) as {
  absolute: Record<string, { limit: number; source: string }>
}
const budget = budgets.absolute['bundleBytes']
if (budget === undefined) throw new Error('bench/budgets.json has no absolute.bundleBytes budget')

await build({
  entryPoints: [path.join(root, 'src', 'cli', 'entry.ts')],
  outfile,
  bundle: true,
  format: 'esm',
  platform: 'node',
  // The floor package.json declares. esbuild then leaves syntax this runtime already has,
  // which is why the bundle is close to the size of the source it carries.
  target: 'node24.15',
  // Not minified, and not source-mapped. A stack trace in a bug report from a machine we
  // cannot reach is worth more than the bytes either would save, and the measured bundle sits
  // at about half the budget, so there is nothing to buy.
  //
  // Read from bin/treadle.js, which carries the reasoning for its plain `#!/usr/bin/env node`
  // line; scripts/shebang.ts refuses anything after `node`.
  banner: { js: shebang },
  legalComments: 'inline',
})

// The shebang only reaches the kernel if the file is executable, and esbuild writes 0644.
// npm sets the mode on a `bin` target when it installs, so this is what makes the bundle
// runnable from a checkout, which is where `--stack-size` was first measured missing.
chmodSync(outfile, 0o755)

const schemas = path.join(root, 'schemas')
mkdirSync(schemas, { recursive: true })
for (const [name, body] of generated()) writeFileSync(path.join(schemas, name), body)

const bytes = statSync(outfile).size
const over = bytes > budget.limit
console.log(
  `bundle: ${bytes} bytes against ${budget.limit} (${budget.source}), ` +
    `${over ? 'OVER' : `${(budget.limit / bytes).toFixed(1)}x under`}`,
)
if (over) process.exitCode = 1
